# config file for "simil" file comparison
[config]
# statements to ignore
ignore = [
    # Python
    "",  # ignore empty lines
    "else:",
    "\"\"\"",
    "\"\"\")",
    "'''",
    "(", ")",
    "{", "}",
    "[", "]",
    "})",
    "continue",
    "break",
    "return",
    "print()",
    "print(",
    "print(\"\"\"",
]
# ignore lines beginning with ...
ignore_beginning = [
    # Python
    "import",
    "from",
    # Rust
    # Rust
    "use",
    "/*", "*/",
    "exit",
    "} else {"
]
trim_whitespace = true