name: Rust
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc-multilib
        run: sudo apt install gcc-multilib
      - name: Install aarch64 toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: aarch64-unknown-linux-gnu
      - name: Build x86
        run: cargo build --release
      - name: Build aarch64
        run: cargo build --release --target=aarch64-unknown-linux-gnu
